version: '3.8'

services:
  mysqlfonte:
    image: mysql:8.0
    container_name: mysqlfonte
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: elmesson
      MYSQL_PASSWORD: elmesson1810
      MYSQL_DATABASE: hopfonte
    ports:
      - "3306:3306"
    networks:
      - redehop
    volumes:
      - ./mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgredestino:
    image: postgres
    container_name: postgredestino
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - redehop
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 10s
      timeout: 5s
      retries: 5

  hopserver:
    image: apache/hop:latest
    container_name: hopserver
    depends_on:
      mysqlfonte:
        condition: service_healthy
      postgredestino:
        condition: service_healthy
    environment:
      HOP_OPTIONS: "-Xmx8192m -Dfile.encoding=UTF8"
      HOP_SERVER_USER: admin
      HOP_SERVER_PASS: admin
      HOP_SERVER_PORT: 8180
      HOP_SERVER_SHUTDOWNPORT: 8080
      HOP_SERVER_HOSTNAME: 0.0.0.0
    ports:
      - "8080:8080"
      - "8180:8180"
      - "8181:8181"
    networks:
      - redehop
    volumes:
      - C:/Users/elmessonjesus/Desktop/Hop/files:/files

networks:
  redehop:
    driver: bridge